---

- hosts: ansible
  become: true
  tasks:

  - name: intall updates on ansible server
    apt:
      upgrade: dist
      update_cache: yes

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
