---

- hosts: all
  become: true
  tasks:

  - name: update repos and install apache and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
