---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache and install available packages (CentOS)
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: update repo cache and install availale packages (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 
    
- hosts: web_servers
  become: true
  roles:
    - web_servers
