---


- hosts: ubuntu
  gather_facts: yes
  become: yes

  tasks:
    - name: Perform a dist-upgrade on Ubuntu hosts
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_distribution == "Ubuntu"

- hosts: centos
  gather_facts: yes
  become: yes

  tasks:

    - name: Upgrade all packages (dnf module)
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS" 

    - name: Install needs-restarting
      ansible.builtin.dnf:
        name: dnf-utils
        state: present
      when: ansible_distribution == "CentOS"

    - name: reboot
      reboot:
      when: reboot_required.rc !=0
