---
- hosts: ubuntu
  gather_facts: yes
  become: yes

  tasks:
    - name: Upgrade packages and handle errors (Ubuntu)
      block:
        - name: Perform a dist-upgrade
          ansible.builtin.apt:
            upgrade: dist
            update_cache: yes
          when: ansible_distribution == "Ubuntu"

        - name: Remove unused dependencies
          ansible.builtin.apt:
            autoremove: yes
          when: ansible_distribution == "Ubuntu"
      rescue:
        - name: Log failure (Ubuntu)
          ansible.builtin.debug:
            msg: "An error occurred during the Ubuntu upgrade process!"

        - name: Potentially run a cleanup task (Ubuntu)
          ansible.builtin.command: echo "Running cleanup..."  # Replace with actual cleanup
          # You might need to use 'failed_when: false' on cleanup commands

- hosts: centos
  gather_facts: yes
  become: yes

  tasks:
    - name: Upgrade and handle errors (CentOS/RedHat)
      block:
        - name: Install needs-restarting (if not present, CentOS)
          ansible.builtin.dnf:
            name: dnf-utils
            state: present
          when: ansible_os_family == "RedHat"

        - name: Upgrade all packages (dnf module)
          ansible.builtin.dnf:
            name: '*'
            state: latest
            update_cache: yes
          when: ansible_os_family == "RedHat"

        - name: Check if reboot required
          ansible.builtin.command: needs-restarting -r  # Use command instead of shell
          failed_when: false
          register: reboot_required
          changed_when: false

        - name: Reboot if required
          ansible.builtin.reboot:
            msg: "Rebooting system due to package updates."
            connect_timeout: 5
            reboot_timeout: 300  # Give it plenty of time to reboot
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: uptime  # Check if the system is back up
          when: reboot_required.rc != 0
      rescue:
        - name: Log failure (CentOS/RedHat)
          ansible.builtin.debug:
            msg: "An error occurred during the CentOS/RedHat upgrade process!"
      always:
        - name: Always run this task (example)
          ansible.builtin.debug:
            msg: "This runs regardless of success or failure."