---


- hosts: ubuntu
  gather_facts: yes
  become: yes

  tasks:
    - name: Perform a dist-upgrade on Ubuntu hosts
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_distribution == "Ubuntu"

- hosts: centos
  gather_facts: yes
  become: yes

  tasks:

    - name: Upgrade all packages
      shell: dnf update -y && dnf upgrade -y

    - name: Check if reboot required
      shell: needs-restarting -r
      failed_when: false
      register: reboot_required
      changed_when: false

    - name: reboot
      reboot:
      when: reboot_required.rc !=0
