---


- hosts: ubuntu
  gather_facts: yes
  become: yes

  tasks:
    - name: Perform a dist-upgrade on Ubuntu hosts
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Check if a reboot is required
      register: file
      stat: path=/var/run/reboot-required get_checksum=no

    - name: Reboot the server
      command: /sbin/reboot
      when: file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_distribution == "Ubuntu"

- hosts: centos
  gather_facts: yes
  become: yes

  tasks:

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Check if reboot required
      shell: needs-restarting -r
      failed_when: false
      register: reboot_required
      changed_when: false

    - name: reboot
      reboot:
      when: reboot_required.rc !=0
